/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.NhanVien_DAO;
import dao.TaiKhoan_DAO;
import entity.ChucVu;
import entity.HinhAnh;
import entity.TaiKhoan;
import entity.NhanVien;
import function.AddImageToData;
import function.ImageScale;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Tan Nghi
 */
public class NguoiQuanLy_ThemNV extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    private NguoiQuanLy_QuanLyNhanVien quanLy;
    private NhanVien_DAO nhanVien_dao;
    private TaiKhoan_DAO taiKhoan_dao;
    private NhanVien nhanVien;
    private TaiKhoan taiKhoan;
    private String anh;
    private AddImageToData image_url;

    public NguoiQuanLy_ThemNV(java.awt.Frame parent, boolean modal, NguoiQuanLy_QuanLyNhanVien quanLy) {
        super(parent, modal);
        this.setUndecorated(true);
        this.quanLy = quanLy;
        nhanVien_dao = new NhanVien_DAO();
        taiKhoan_dao = new TaiKhoan_DAO();
        nhanVien = null;
        taiKhoan = null;
        initComponents();


        setLocationRelativeTo(null);
        try {
            jTextField_MaNhanVien.setText(createMaNhanVien());
            jTextField_TenDangNhap.setText(createMaNhanVien());
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private NguoiQuanLy_ThemNV(java.awt.Frame parent, boolean modal) {

    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            Color colorl = new Color(238, 223, 204);
            Color color2 = new Color(255, 245, 238);
            GradientPaint gp = new GradientPaint(0, 0, colorl, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    class jPanelTongGradient extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g); // Ensures proper painting behavior
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            Color colorl = new Color(139, 119, 101);
            Color color2 = new Color(205, 175, 149);
            GradientPaint gp = new GradientPaint(0, 0, colorl, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelTongGradient();
        jLabel_ThemNhanVien = new javax.swing.JLabel();
        jPanel2 = new jPanelGradient();
        jLabel_MaNhanVien = new javax.swing.JLabel();
        jLabel_TenNhanVien = new javax.swing.JLabel();
        jLabel_GioiTinh = new javax.swing.JLabel();
        jLabel_SoDienThoai = new javax.swing.JLabel();
        jLabel_ChucVu = new javax.swing.JLabel();
        jLabel_TenDangNhap = new javax.swing.JLabel();
        jLabel_MatKhau = new javax.swing.JLabel();
        jLabel_BatBuoc4 = new javax.swing.JLabel();
        jLabel_BatBuoc1 = new javax.swing.JLabel();
        jLabel_BatBuoc2 = new javax.swing.JLabel();
        jButton_Luu = new javax.swing.JButton();
        jButton_HuyBo = new javax.swing.JButton();
        jLabel_BatBuoc3 = new javax.swing.JLabel();
        jTextField_TenNhanVien = new javax.swing.JTextField();
        jTextField_MaNhanVien = new javax.swing.JTextField();
        jComboBox_GioiTinh = new javax.swing.JComboBox<>();
        jLabel_NgaySinh = new javax.swing.JLabel();
        jTextField_SoDienThoai = new javax.swing.JTextField();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_TenDangNhap = new javax.swing.JTextField();
        jDateChooser_NgaySinh = new com.toedter.calendar.JDateChooser();
        jButton_ThemAnh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_AnhDaiDien = new javax.swing.JLabel();
        jLabel_TenDangNhap1 = new javax.swing.JLabel();
        jTextField_DiaChi = new javax.swing.JTextField();
        jTextField_MatKhau = new javax.swing.JTextField();
        jComboBox_ChucVu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1214, 773));

        jLabel_ThemNhanVien.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel_ThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ThemNhanVien.setText("Thêm nhân viên");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 20));

        jLabel_MaNhanVien.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_MaNhanVien.setText("Mã nhân viên");

        jLabel_TenNhanVien.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TenNhanVien.setText("Tên nhân viên");

        jLabel_GioiTinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_GioiTinh.setText("Giới tính");

        jLabel_SoDienThoai.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_SoDienThoai.setText("Số điện thoại");

        jLabel_ChucVu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_ChucVu.setText("Chức vụ");

        jLabel_TenDangNhap.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TenDangNhap.setText("Tên đăng nhập");

        jLabel_MatKhau.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_MatKhau.setText("Mật khẩu");

        jLabel_BatBuoc4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_BatBuoc4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_BatBuoc4.setText("(*)");

        jLabel_BatBuoc1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_BatBuoc1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_BatBuoc1.setText("(*)");

        jLabel_BatBuoc2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_BatBuoc2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_BatBuoc2.setText("(*)");

        jButton_Luu.setBackground(new java.awt.Color(102, 102, 0));
        jButton_Luu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_Luu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Luu.setText("Thêm");
        jButton_Luu.setBorder(null);
        jButton_Luu.setPreferredSize(new java.awt.Dimension(52, 24));
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_HuyBo.setBackground(new java.awt.Color(153, 0, 51));
        jButton_HuyBo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_HuyBo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_HuyBo.setText("Hủy");
        jButton_HuyBo.setMaximumSize(new java.awt.Dimension(52, 24));
        jButton_HuyBo.setMinimumSize(new java.awt.Dimension(52, 24));
        jButton_HuyBo.setPreferredSize(new java.awt.Dimension(52, 24));
        jButton_HuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyBoActionPerformed(evt);
            }
        });

        jLabel_BatBuoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_BatBuoc3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_BatBuoc3.setText("(*)");

        jTextField_TenNhanVien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_TenNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_MaNhanVien.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_MaNhanVien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_MaNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_MaNhanVien.setFocusable(false);

        jComboBox_GioiTinh.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_GioiTinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jComboBox_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jComboBox_GioiTinh.setBorder(null);
        jComboBox_GioiTinh.setPreferredSize(new java.awt.Dimension(64, 28));

        jLabel_NgaySinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_NgaySinh.setText("Ngày sinh");
        jLabel_NgaySinh.setPreferredSize(new java.awt.Dimension(79, 22));

        jTextField_SoDienThoai.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_SoDienThoai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Email.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_Email.setText("Email");

        jTextField_Email.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_Email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_TenDangNhap.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_TenDangNhap.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_TenDangNhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_TenDangNhap.setFocusable(false);

        jDateChooser_NgaySinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        jButton_ThemAnh.setBackground(new java.awt.Color(102, 102, 0));
        jButton_ThemAnh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_ThemAnh.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThemAnh.setText("Thêm ảnh");
        jButton_ThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemAnhActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(327, 342));
        jPanel3.setRequestFocusEnabled(false);

        jLabel_AnhDaiDien.setPreferredSize(new java.awt.Dimension(327, 342));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel_AnhDaiDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel_AnhDaiDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel_TenDangNhap1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TenDangNhap1.setText("Địa chỉ");

        jTextField_DiaChi.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_DiaChi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_MatKhau.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_MatKhau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox_ChucVu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jComboBox_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thủ kho", "Nhân viên" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_SoDienThoai)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_BatBuoc1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_TenNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_BatBuoc2))
                            .addComponent(jLabel_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_TenDangNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_BatBuoc4)
                            .addComponent(jLabel_BatBuoc3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel_MatKhau))
                    .addComponent(jLabel_TenDangNhap1))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(jTextField_TenDangNhap)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Email))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_TenNhanVien)
                    .addComponent(jTextField_MaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(jTextField_MatKhau)
                    .addComponent(jComboBox_ChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton_ThemAnh))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_BatBuoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_BatBuoc2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Email)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox_ChucVu)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenDangNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_BatBuoc3))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_BatBuoc4)
                    .addComponent(jTextField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton_ThemAnh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_ThemNhanVien)
                        .addGap(0, 1055, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_ThemNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(493, 493, 493))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyBoActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thoát", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setVisible(false);
        }
    }//GEN-LAST:event_jButton_HuyBoActionPerformed
    private boolean kiemTraTenNV(String ten) {
        String regex = "^[\\p{L}]+(?:[\\s.'-][\\p{L}]+)*$";
//        1. ^ và $ xác định bắt đầu và kết thúc chuỗi.
//        2. \\p{L} đại diện cho bất kỳ ký tự chữ nào (bao gồm cả chữ cái có dấu từ nhiều ngôn ngữ khác nhau).
//        3. + yêu cầu ít nhất một ký tự chữ đầu tiên trong tên.
//        4. (?: ... )* là nhóm không bắt buộc lặp lại nhiều lần. Bên trong nhóm này:
//                  [\\s.'-] cho phép khoảng trắng, dấu chấm (.), dấu nháy đơn ('), hoặc dấu gạch ngang (-) giữa các từ.
//                  \\p{L}+ yêu cầu ít nhất một ký tự chữ sau khoảng trắng hoặc dấu.
//          VD:
//                "Nguyễn Văn A"
//                "O'Neill"
//                "Trần Minh-Châu"
//                "Lê Hữu Đ."
        return ten.matches(regex);
    }

    private boolean kiemTraNgaySinh(LocalDate ngaySinh) {
        if (ngaySinh != null) {
            LocalDate today = LocalDate.now();

            // Tính số năm tuổi
            int age = Period.between(ngaySinh, today).getYears();

            // Kiểm tra tuổi có đủ 18 hay không
            return age >= 18;
        } else {
            // Trường hợp ngày sinh chưa được cung cấp
            return false;
        }
    }

    private boolean kiemTraSDT(String sDT) {
        String regex = "^\\d{10}$";
        return sDT != null && sDT.matches(regex);
    }

    private boolean kiemTraEmail(String email) {
        String regex = "^(?!\\.)[a-zA-Z0-9._%+-]+(?<!\\.)@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
//            1. ^(?!\\.): Đảm bảo chuỗi không bắt đầu bằng dấu chấm (.).
//            2. [a-zA-Z0-9._%+-]+: Cho phép các ký tự chữ cái, số và các ký tự ._%+- trong phần tên email.
//            3. (?<!\\.): Đảm bảo chuỗi không kết thúc bằng dấu chấm (.).
//            4. @: Ký tự bắt buộc phân chia phần tên email và phần tên miền.
//            5. [a-zA-Z0-9.-]+: Cho phép các ký tự chữ cái, số và dấu gạch ngang (-) trong phần tên miền.
//            6. \\.[a-zA-Z]{2,}$: Kiểm tra phần mở rộng của tên miền với ít nhất 2 ký tự chữ cái.
//            VD email hợp lệ:
//                example@gmail.com
//                user.name@domain.com
//                my-email+tag@sub.domain.org
//            VD email không hợp lệ:
//                user..name@domain.com (dấu chấm liên tiếp trong phần tên email).
//                .username@domain.com (dấu chấm ở đầu phần tên).
//                username.@domain.com (dấu chấm ở cuối phần tên).
        return email.matches(regex);
    }

    private boolean kiemTraDiaChi(String diaChi) {
        String regex = "^[\\p{L}\\d\\s.,-/]+$";
//        1. ^ và $: Xác định bắt đầu và kết thúc chuỗi.
//        2. \\p{L}: Cho phép các ký tự chữ từ nhiều ngôn ngữ (bao gồm cả tiếng Việt có dấu).
//        3. \\d: Cho phép các chữ số.
//        4. \\s: Cho phép khoảng trắng.
//        5. [.,-/]: Cho phép các ký tự đặc biệt phổ biến trong địa chỉ (dấu chấm, dấu phẩy, gạch chéo, và gạch ngang).
//        6. +: Yêu cầu chuỗi phải có ít nhất một ký tự hợp lệ và có thể lặp lại nhiều lần.
//          VD:
//                "123 Đường Láng, P. Láng Hạ, Q. Đống Đa"
//                "Số 5 Ngõ 7, Phố Trần Duy Hưng"
//                "12A-B Phường 5, Quận 3, TP.HCM"
//                "1/234 Khu phố Tân Phong - Thủ Đức"
        return diaChi.matches(regex);
    }

    private boolean kiemTraTatCa() {
        String tenNhanVien = jTextField_TenNhanVien.getText();
        Date date = jDateChooser_NgaySinh.getDate();

        String soDienThoai = jTextField_SoDienThoai.getText();
        String email = jTextField_Email.getText();
        String diaChi = jTextField_DiaChi.getText();
        // Kiểm tra từng điều kiện và hiển thị thông báo nếu có lỗi
        if (tenNhanVien.trim().isEmpty() || !kiemTraTenNV(tenNhanVien)) {
            JOptionPane.showMessageDialog(this, "Tên nhân viên không hợp lệ!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            jTextField_TenNhanVien.requestFocus();
            jTextField_TenNhanVien.selectAll();
            return false;
        }

        // Kiểm tra ngày sinh
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        LocalDate ngaySinh = date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        if (!kiemTraNgaySinh(ngaySinh)) {
            JOptionPane.showMessageDialog(this, "Nhân viên phải trên 18 tuổi!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        if (soDienThoai.trim().isEmpty() || !kiemTraSDT(soDienThoai)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            jTextField_SoDienThoai.requestFocus();
            jTextField_SoDienThoai.selectAll();
            return false;
        }

        if (email.trim().isEmpty() || !kiemTraEmail(email)) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            jTextField_Email.requestFocus();
            jTextField_Email.selectAll();
            return false;
        }

        if (diaChi.trim().isEmpty() || !kiemTraDiaChi(diaChi)) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không hợp lệ!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            jTextField_DiaChi.requestFocus();
            jTextField_DiaChi.selectAll();
            return false;
        }
        if (anh == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ảnh đại diện!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        // Nếu tất cả kiểm tra đều hợp lệ
        return true;
    }

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_jButton_LuuActionPerformed
        // TODO add your handling code here:
        boolean kiemTra = kiemTraTatCa();

        if (kiemTra) {
            String tenNhanVien = jTextField_TenNhanVien.getText();
            String gioiTinh = jComboBox_GioiTinh.getSelectedItem().toString();
            String soDienThoai = jTextField_SoDienThoai.getText();
            String chucVu = jComboBox_ChucVu.getSelectedItem().toString();
            String matKhau = jTextField_MatKhau.getText();
            String diaChi = jTextField_DiaChi.getText();
            String email = jTextField_Email.getText();
            LocalDate ngaySinh = jDateChooser_NgaySinh.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();;
            boolean gt = gioiTinh.equals("Nam") ? false : true;
            try {
                nhanVien = new NhanVien(tenNhanVien, soDienThoai, diaChi, email, gt, ngaySinh, createMaNhanVien(), new ChucVu(chucVu), new HinhAnh(anh), "Đang làm");

                if (nhanVien_dao.themNhanVien(nhanVien)) {
                    taiKhoan = new TaiKhoan(createMaTaiKhoan(), nhanVien, matKhau);

                    if (taiKhoan_dao.themTaiKhoan(taiKhoan)) {
                        quanLy.addDataToTable(nhanVien);
                        JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
                        setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại");
                    }
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }


    }//GEN-LAST:event_jButton_LuuActionPerformed
    private void jButton_ThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser frame_chonAnh = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("File ảnh", "png", "jpq", "jpeg", "gif");
        frame_chonAnh.setFileFilter(filter);
        frame_chonAnh.setAcceptAllFileFilterUsed(false);

        int returnValue = frame_chonAnh.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String filePath = frame_chonAnh.getSelectedFile().getPath();
            Icon icon = new ImageScale().load(filePath, jLabel_AnhDaiDien.getWidth(), jLabel_AnhDaiDien.getHeight());
            jLabel_AnhDaiDien.setIcon(icon);
            image_url = new AddImageToData();
            String fileName = image_url.duaFileVaoThuMuc(new File(filePath), "src\\ServiceImage\\NhanVien_IMG", "../ServiceImage/NhanVien_IMG/");
            System.out.println(fileName);
            anh = fileName;
        }
    }//GEN-LAST:event_jButton_ThemAnhActionPerformed
    public String createMaNhanVien() throws SQLException {
        List<String> dsMa = new ArrayList<>();
        for (NhanVien x : nhanVien_dao.getDSNhanVien()) {
            dsMa.add(x.getMaNV());
        }
        String lastMaNhanVien = dsMa.get(dsMa.size() - 1);
        int number = Integer.parseInt(lastMaNhanVien) + 1;
        return String.valueOf(number);

    }

    public String createMaTaiKhoan() throws SQLException {
        List<String> dsMaTK = taiKhoan_dao.getMaTK();
        String lastMaTaiKhoan = dsMaTK.get(dsMaTK.size() - 1);
        String prefix = lastMaTaiKhoan.substring(0, 2);
        String number = lastMaTaiKhoan.substring(2);
        int numberInt = Integer.parseInt(number);
        numberInt++;
        String newNumber = String.format("%03d", numberInt);
        return prefix + newNumber;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NguoiQuanLy_ThemNV dialog = new NguoiQuanLy_ThemNV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_HuyBo;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_ThemAnh;
    private javax.swing.JComboBox<String> jComboBox_ChucVu;
    private javax.swing.JComboBox<String> jComboBox_GioiTinh;
    private com.toedter.calendar.JDateChooser jDateChooser_NgaySinh;
    private javax.swing.JLabel jLabel_AnhDaiDien;
    private javax.swing.JLabel jLabel_BatBuoc1;
    private javax.swing.JLabel jLabel_BatBuoc2;
    private javax.swing.JLabel jLabel_BatBuoc3;
    private javax.swing.JLabel jLabel_BatBuoc4;
    private javax.swing.JLabel jLabel_ChucVu;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_GioiTinh;
    private javax.swing.JLabel jLabel_MaNhanVien;
    private javax.swing.JLabel jLabel_MatKhau;
    private javax.swing.JLabel jLabel_NgaySinh;
    private javax.swing.JLabel jLabel_SoDienThoai;
    private javax.swing.JLabel jLabel_TenDangNhap;
    private javax.swing.JLabel jLabel_TenDangNhap1;
    private javax.swing.JLabel jLabel_TenNhanVien;
    private javax.swing.JLabel jLabel_ThemNhanVien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_MaNhanVien;
    private javax.swing.JTextField jTextField_MatKhau;
    private javax.swing.JTextField jTextField_SoDienThoai;
    private javax.swing.JTextField jTextField_TenDangNhap;
    private javax.swing.JTextField jTextField_TenNhanVien;
    // End of variables declaration//GEN-END:variables
}
