/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author phamd
 */
public class NguoiQuanLy_ThongKeTonKho extends javax.swing.JInternalFrame {

    /**
     * Creates new form NguoiQuanLy_ThongKeTonKho
     */
    public NguoiQuanLy_ThongKeTonKho() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_NameOfBook = new javax.swing.JTextField();
        jComboBox_ISBN = new javax.swing.JComboBox<>();
        jComboBox_TênKho = new javax.swing.JComboBox<>();
        jButton_ThongKeTonKho = new javax.swing.JButton();
        jButton_LamMoi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane_TonKho = new javax.swing.JScrollPane();
        jTable_ThongKeTonKho = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1479, 677));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1503, 500));

        jTextField_NameOfBook.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_NameOfBook.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_NameOfBook.setText("Nhập tên sách");
        jTextField_NameOfBook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NameOfBookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NameOfBookFocusLost(evt);
            }
        });

        jComboBox_ISBN.setBackground(new java.awt.Color(102, 102, 0));
        jComboBox_ISBN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox_ISBN.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_ISBN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"ISBN"}));
        jComboBox_ISBN.setBorder(null);
        jComboBox_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ISBNActionPerformed(evt);
            }
        });

        jComboBox_TênKho.setBackground(new java.awt.Color(102, 102, 0));
        jComboBox_TênKho.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox_TênKho.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_TênKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên kho", " " }));
        jComboBox_TênKho.setBorder(null);
        jComboBox_TênKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TênKhoActionPerformed(evt);
            }
        });

        jButton_ThongKeTonKho.setBackground(new java.awt.Color(102, 102, 0));
        jButton_ThongKeTonKho.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_ThongKeTonKho.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThongKeTonKho.setText("Thống kê");

        jButton_LamMoi.setBackground(new java.awt.Color(255, 0, 0));
        jButton_LamMoi.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
        jButton_LamMoi.setText("Làm mới");

        jButton2.setBackground(new java.awt.Color(102, 102, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xuất Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane_TonKho.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane_TonKho.setDoubleBuffered(true);
        jScrollPane_TonKho.setEnabled(false);

        jTable_ThongKeTonKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ISBN", "Tên sách", "Tên kho", "Tồn kho", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_ThongKeTonKho.setShowGrid(true);
        JTableHeader tableHeader = jTable_ThongKeTonKho.getTableHeader();
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) tableHeader.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);

        TableColumnModel columnModel = jTable_ThongKeTonKho.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(25); // Đặt độ rộng cho cột 0
        columnModel.getColumn(1).setPreferredWidth(50); // Đặt độ rộng cho cột 1
        columnModel.getColumn(2).setPreferredWidth(175);
        columnModel.getColumn(3).setPreferredWidth(175);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(150);
        // Tương tự cho các cột khác nếu cần
        jTable_ThongKeTonKho.getTableHeader().setFont(new Font("Arial", Font.BOLD, 20));
        jTable_ThongKeTonKho.setFont(new Font("Arial", Font.PLAIN, 18));
        jScrollPane_TonKho.setViewportView(jTable_ThongKeTonKho);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_LamMoi)
                .addGap(57, 57, 57))
            .addComponent(jScrollPane_TonKho, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_NameOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_TênKho, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ThongKeTonKho)
                .addContainerGap(747, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NameOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_TênKho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ThongKeTonKho))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane_TonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton_LamMoi)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ISBNActionPerformed

    private void jComboBox_TênKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TênKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TênKhoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_NameOfBookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameOfBookFocusGained
        if(jTextField_NameOfBook.getText().equals("Nhập tên sách")){
            jTextField_NameOfBook.setText("");
            jTextField_NameOfBook.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField_NameOfBookFocusGained

    private void jTextField_NameOfBookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameOfBookFocusLost
        if(jTextField_NameOfBook.getText().equals("")){
            jTextField_NameOfBook.setText("Nhập tên sách");
            jTextField_NameOfBook.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextField_NameOfBookFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_ThongKeTonKho;
    private javax.swing.JComboBox<String> jComboBox_ISBN;
    private javax.swing.JComboBox<String> jComboBox_TênKho;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane_TonKho;
    private javax.swing.JTable jTable_ThongKeTonKho;
    private javax.swing.JTextField jTextField_NameOfBook;
    // End of variables declaration//GEN-END:variables
}
