/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.TaiKhoan_DAO;
import entity.ChucVu;
import entity.HinhAnh;
import entity.TaiKhoan;
import function.AddImageToData;
import function.ImageScale;
import entity.NhanVien;

import java.awt.*;
import java.io.File;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Period;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Tan Nghi
 */
public class NguoiQuanLy_ChinhSuaNhanVien extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    private NguoiQuanLy_QuanLyNhanVien quanLy;
    private NhanVien nhanVien;
    private String anh;
    private AddImageToData image_url;
    private TaiKhoan_DAO tkDAO;
    private TaiKhoan taiKhoan;
    private boolean checkTrue = false;

    public NguoiQuanLy_ChinhSuaNhanVien(java.awt.Frame parent, boolean modal, NguoiQuanLy_QuanLyNhanVien quanLy, NhanVien nhanVien) {
        super(parent, modal);
        this.setUndecorated(true);
        this.quanLy = quanLy;
        tkDAO = new TaiKhoan_DAO();
        initComponents();
        setLocationRelativeTo(null);
        try {
            initialData(nhanVien);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private NguoiQuanLy_ChinhSuaNhanVien(java.awt.Frame parent, boolean modal) {

    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            Color colorl = new Color(238, 223, 204);
            Color color2 = new Color(255, 245, 238);
            GradientPaint gp = new GradientPaint(0, 0, colorl, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    class jPanelTongGradient extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g); // Ensures proper painting behavior
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            Color colorl = new Color(139, 119, 101);
            Color color2 = new Color(205, 175, 149);
            GradientPaint gp = new GradientPaint(0, 0, colorl, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelTongGradient();
        jLabel_ThemNhanVien = new javax.swing.JLabel();
        jPanel2 = new jPanelGradient();
        jLabel_MaNhanVien = new javax.swing.JLabel();
        jLabel_TenNhanVien = new javax.swing.JLabel();
        jLabel_GioiTinh = new javax.swing.JLabel();
        jLabel_SoDienThoai = new javax.swing.JLabel();
        jLabel_ChucVu = new javax.swing.JLabel();
        jLabel_TenDangNhap = new javax.swing.JLabel();
        jLabel_MatKhau = new javax.swing.JLabel();
        jButton_Luu = new javax.swing.JButton();
        jButton_HuyBo = new javax.swing.JButton();
        jTextField_TenNhanVien = new javax.swing.JTextField();
        jTextField_MaNhanVien = new javax.swing.JTextField();
        jComboBox_GioiTinh = new javax.swing.JComboBox<>();
        jLabel_NgaySinh = new javax.swing.JLabel();
        jTextField_SoDienThoai = new javax.swing.JTextField();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_TenDangNhap = new javax.swing.JTextField();
        jDateChooser_NgaySinh = new com.toedter.calendar.JDateChooser();
        jButton_ThemAnh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Anh = new javax.swing.JLabel();
        jTextField_MatKhau = new javax.swing.JTextField();
        jLabel_ChucVu1 = new javax.swing.JLabel();
        jTextField_DiaChi = new javax.swing.JTextField();
        jComboBox_ChucVu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1214, 773));

        jLabel_ThemNhanVien.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel_ThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ThemNhanVien.setText("Cập nhật thông tin nhân viên");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 20));

        jLabel_MaNhanVien.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_MaNhanVien.setText("Mã nhân viên");

        jLabel_TenNhanVien.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TenNhanVien.setText("Tên nhân viên");

        jLabel_GioiTinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_GioiTinh.setText("Giới tính");

        jLabel_SoDienThoai.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_SoDienThoai.setText("Số điện thoại");

        jLabel_ChucVu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_ChucVu.setText("Chức vụ");

        jLabel_TenDangNhap.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TenDangNhap.setText("Tên đăng nhập");

        jLabel_MatKhau.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_MatKhau.setText("Mật khẩu");

        jButton_Luu.setBackground(new java.awt.Color(102, 102, 0));
        jButton_Luu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_Luu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Luu.setText("Lưu");
        jButton_Luu.setBorder(null);
        jButton_Luu.setPreferredSize(new java.awt.Dimension(52, 24));
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_HuyBo.setBackground(new java.awt.Color(153, 0, 51));
        jButton_HuyBo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_HuyBo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_HuyBo.setText("Hủy");
        jButton_HuyBo.setMaximumSize(new java.awt.Dimension(52, 24));
        jButton_HuyBo.setMinimumSize(new java.awt.Dimension(52, 24));
        jButton_HuyBo.setPreferredSize(new java.awt.Dimension(52, 24));
        jButton_HuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyBoActionPerformed(evt);
            }
        });

        jTextField_TenNhanVien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_TenNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_TenNhanVien.setOpaque(true);

        jTextField_MaNhanVien.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_MaNhanVien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_MaNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_MaNhanVien.setFocusable(false);

        jComboBox_GioiTinh.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_GioiTinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jComboBox_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jComboBox_GioiTinh.setBorder(null);
        jComboBox_GioiTinh.setPreferredSize(new java.awt.Dimension(64, 28));

        jLabel_NgaySinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_NgaySinh.setText("Ngày sinh");
        jLabel_NgaySinh.setPreferredSize(new java.awt.Dimension(79, 22));

        jTextField_SoDienThoai.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_SoDienThoai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Email.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_Email.setText("Email");

        jTextField_Email.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_Email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_TenDangNhap.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_TenDangNhap.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_TenDangNhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_TenDangNhap.setFocusable(false);

        jDateChooser_NgaySinh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        jButton_ThemAnh.setBackground(new java.awt.Color(102, 102, 0));
        jButton_ThemAnh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_ThemAnh.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThemAnh.setText("Thêm ảnh");
        jButton_ThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemAnhActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(327, 342));
        jPanel3.setRequestFocusEnabled(false);

        jLabel_Anh.setPreferredSize(new java.awt.Dimension(327, 342));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel_Anh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel_Anh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTextField_MatKhau.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_MatKhau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_ChucVu1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_ChucVu1.setText("Địa chỉ");

        jTextField_DiaChi.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_DiaChi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox_ChucVu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jComboBox_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Thủ kho" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_TenNhanVien)
                                .addComponent(jLabel_GioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_SoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_ChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_ChucVu1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_TenDangNhap, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_MatKhau, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Email))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_TenNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_MaNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(jTextField_TenDangNhap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_MatKhau, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_DiaChi)
                    .addComponent(jComboBox_ChucVu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(181, 181, 181)
                            .addComponent(jButton_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(jButton_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButton_ThemAnh)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Email)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton_ThemAnh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_ThemNhanVien)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel_ThemNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(443, 443, 443))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyBoActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Ban chac chan muon thoat", "Canh bao", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setVisible(false);
        }
    }//GEN-LAST:event_jButton_HuyBoActionPerformed

    private void jButton_ThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser frame_chonAnh = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("File ảnh", "png", "jpq", "jpeg", "gif");
        frame_chonAnh.setFileFilter(filter);
        frame_chonAnh.setAcceptAllFileFilterUsed(false);
        int returnValue = frame_chonAnh.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String filePath = frame_chonAnh.getSelectedFile().getPath();
            Icon icon = new ImageScale().load(filePath, jLabel_Anh.getWidth(), jLabel_Anh.getHeight());
            jLabel_Anh.setIcon(icon);
            image_url = new AddImageToData();
            String fileName = image_url.duaFileVaoThuMuc(new File(filePath), "src\\ServiceImage\\NhanVien_IMG", "../ServiceImage/NhanVien_IMG/");
            anh = fileName;
        }
    }//GEN-LAST:event_jButton_ThemAnhActionPerformed
    private boolean kiemTraTenNV(String ten) {
        String regex = "^[\\p{L}]+(?:[\\s.'-][\\p{L}]+)*$";
        return ten.matches(regex);
    }

    private boolean kiemTraDiaChi(String diaChi) {
        String regex = "^[\\p{L}\\d\\s.,-/]+$";
        return diaChi.matches(regex);
    }

    private boolean kiemTraEmail(String email) {
        String regex = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
        return email.matches(regex);
    }
    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt)   {//GEN-FIRST:event_jButton_LuuActionPerformed
        // TODO add your handling code here:
        NhanVien nv = newData();
        System.out.println(nv);

        try {
            if(checkTrue){
                quanLy.editDataToTable(nv);
                this.dispose();
            }
            
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void initialData(NhanVien nhanVien) throws SQLException {
        taiKhoan = tkDAO.getTaiKhoanTheoTenDN(nhanVien.getMaNV());
        jTextField_MaNhanVien.setText(nhanVien.getMaNV());
        jTextField_TenNhanVien.setText(nhanVien.getHoTen());
        jComboBox_GioiTinh.setSelectedItem(nhanVien.isGioiTinh() ? "Nữ" : "Nam");
        jDateChooser_NgaySinh.setDate(java.sql.Date.valueOf(nhanVien.getNgaySinh()));
        jTextField_SoDienThoai.setText(nhanVien.getSoDienThoai());
        jTextField_SoDienThoai.setText(nhanVien.getSoDienThoai());
        jTextField_Email.setText(nhanVien.getEmail());
        jTextField_DiaChi.setText(nhanVien.getChucVu().getChucVu());
        jTextField_TenDangNhap.setText(taiKhoan.getNhanVien().getMaNV());
        jTextField_MatKhau.setText(taiKhoan.getMatKhau());
        jTextField_DiaChi.setText(nhanVien.getDiaChi());
        jComboBox_ChucVu.setSelectedItem(nhanVien.getChucVu().getChucVu());
        String duongDanChinh = nhanVien.getAnh().getUrl().replace("..", "src");
        File fileAnh = new File(duongDanChinh);
        String duongDanTuyetDoi = fileAnh.getAbsolutePath();
        ImageIcon image = new ImageIcon(duongDanTuyetDoi);
        Image imageFit = image.getImage().getScaledInstance(jLabel_Anh.getWidth(), jLabel_Anh.getHeight(), Image.SCALE_SMOOTH);
        jLabel_Anh.setIcon(new ImageIcon(imageFit));
        anh = nhanVien.getAnh().getUrl();
        System.out.println(anh);
    }

    public NhanVien newData() 
    {
        boolean kiemTra = false;
        boolean tam = false;
        while (!kiemTra) {
            if (!kiemTraTenNV(jTextField_TenNhanVien.getText()) || jTextField_TenNhanVien.getText().equalsIgnoreCase("")) {
                jTextField_TenNhanVien.selectAll();
                jTextField_TenNhanVien.requestFocus();
                JOptionPane.showConfirmDialog(this, "Tên nhân viên không hợp lệ", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                tam = true;
                break;
            } else if (!kiemTraEmail(jTextField_Email.getText()) || jTextField_Email.getText().equalsIgnoreCase("")) {
                jTextField_Email.selectAll();
                jTextField_Email.requestFocus();
                JOptionPane.showConfirmDialog(this, "Email không hợp lệ", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                tam = true;
                break;
            } else if (!kiemTraDiaChi(jTextField_DiaChi.getText()) || jTextField_DiaChi.getText().equalsIgnoreCase("")) {
                jTextField_DiaChi.selectAll();
                jTextField_DiaChi.requestFocus();
                JOptionPane.showConfirmDialog(this, "Địa chỉ không hợp lệ", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                tam = true;
                break;
            } else {
                kiemTra = true;
            }
        }
        LocalDate ngaySinh = null;
        if (!tam) {
            if (jDateChooser_NgaySinh.getDate() != null) {
                // Lấy ngày sinh từ jDateChooser
                ngaySinh = jDateChooser_NgaySinh.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

                // Kiểm tra tuổi của nhân viên
                LocalDate today = LocalDate.now();
                int age = Period.between(ngaySinh, today).getYears();

                if (age < 18) {
                    JOptionPane.showMessageDialog(this, "Nhân viên phải từ 18 tuổi trở lên.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                    return null;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return null;

            }

            // Kiểm tra số điện thoại là số hợp lệ
            try {
                Long.parseLong(jTextField_SoDienThoai.getText());
                if (!jTextField_SoDienThoai.getText().matches("^\\d{10}$")) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại phải là 10 chữ số.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                    jTextField_SoDienThoai.selectAll();
                    jTextField_SoDienThoai.requestFocus();

                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số điện thoại phải là một số hợp lệ.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                jTextField_SoDienThoai.selectAll();
                jTextField_SoDienThoai.requestFocus();

            }
            kiemTra=true;
        }

        // Kiểm tra nếu chưa chọn ảnh
        if (anh == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ảnh đại diện");
        }
        NhanVien nhanVien = new NhanVien();
        if (kiemTra) {
            nhanVien.setMaNV(jTextField_MaNhanVien.getText());
            nhanVien.setHoTen(jTextField_TenNhanVien.getText());
            nhanVien.setGioiTinh(jComboBox_GioiTinh.getSelectedItem().toString().equals("Nam") ? false : true);
            nhanVien.setNgaySinh(jDateChooser_NgaySinh.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate());
            nhanVien.setSoDienThoai(jTextField_SoDienThoai.getText());
            nhanVien.setEmail(jTextField_Email.getText());
            nhanVien.setDiaChi(jTextField_DiaChi.getText());
            nhanVien.setChucVu(new ChucVu((String) jComboBox_ChucVu.getSelectedItem()));
            nhanVien.setAnh(new HinhAnh(anh));
            checkTrue = true;
        }
          return nhanVien;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ChinhSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ChinhSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ChinhSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiQuanLy_ChinhSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NguoiQuanLy_ChinhSuaNhanVien dialog = new NguoiQuanLy_ChinhSuaNhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_HuyBo;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_ThemAnh;
    private javax.swing.JComboBox<String> jComboBox_ChucVu;
    private javax.swing.JComboBox<String> jComboBox_GioiTinh;
    private com.toedter.calendar.JDateChooser jDateChooser_NgaySinh;
    private javax.swing.JLabel jLabel_Anh;
    private javax.swing.JLabel jLabel_ChucVu;
    private javax.swing.JLabel jLabel_ChucVu1;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_GioiTinh;
    private javax.swing.JLabel jLabel_MaNhanVien;
    private javax.swing.JLabel jLabel_MatKhau;
    private javax.swing.JLabel jLabel_NgaySinh;
    private javax.swing.JLabel jLabel_SoDienThoai;
    private javax.swing.JLabel jLabel_TenDangNhap;
    private javax.swing.JLabel jLabel_TenNhanVien;
    private javax.swing.JLabel jLabel_ThemNhanVien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_MaNhanVien;
    private javax.swing.JTextField jTextField_MatKhau;
    private javax.swing.JTextField jTextField_SoDienThoai;
    private javax.swing.JTextField jTextField_TenDangNhap;
    private javax.swing.JTextField jTextField_TenNhanVien;
    // End of variables declaration//GEN-END:variables
}
