/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.ChiTietKhoHang_DAO;
import dao.KhoHang_DAO;
import entity.*;
import function.AddImageToData;
import function.ImageScale;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystemException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Tan Nghi
 */
public class Sach_ThemSach extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    private Sach_QuanLySach dsSach;
    private String anh;
    private AddImageToData image_url;
    private KhoHang_DAO khoHang_dao;
    private ChiTietKhoHang_DAO chiTietKhoHang_dao;
    public Sach_ThemSach(java.awt.Frame parent, boolean modal, Sach_QuanLySach dsSach) {
        super(parent, modal);
        this.setUndecorated(true);
        this.dsSach = dsSach;
        chiTietKhoHang_dao = new ChiTietKhoHang_DAO();
        initComponents();
        setLocationRelativeTo(null);

        
    }
    private Sach_ThemSach(java.awt.Frame parent, boolean modal){
        
    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            Color colorl = new Color(238, 223, 204);
            Color color2 = new Color(255, 245, 238);
            GradientPaint gp = new GradientPaint(0, 0, colorl, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    class jPanelTongGradient extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g); // Ensures proper painting behavior
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            Color colorl = new Color(139, 119, 101);
            Color color2 = new Color(205, 175, 149);
            GradientPaint gp = new GradientPaint(0, 0, colorl, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelTongGradient();
        jLabel_ThemNhanVien = new javax.swing.JLabel();
        jPanel2 = new jPanelGradient();
        jLabel_ISBN = new javax.swing.JLabel();
        jLabel_TenSach = new javax.swing.JLabel();
        jLabel_DonGia = new javax.swing.JLabel();
        jLabel_TenLoaiSach = new javax.swing.JLabel();
        jLabel_TacGia = new javax.swing.JLabel();
        jLabel_NhaXuatBan = new javax.swing.JLabel();
        jLabel_NamXuatBan = new javax.swing.JLabel();
        jButton_ThemSach = new javax.swing.JButton();
        jButton_HuyBo = new javax.swing.JButton();
        jTextField_TenSach = new javax.swing.JTextField();
        jTextField_ISBN = new javax.swing.JTextField();
        jTextField_TacGia = new javax.swing.JTextField();
        jTextField_NhaXuatBan = new javax.swing.JTextField();
        jTextField_NamXuatBan = new javax.swing.JTextField();
        jButton_ThemAnh = new javax.swing.JButton();
        jTextField_DonGia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel_AnhDaiDien = new javax.swing.JLabel();
        jComboBox_LoaiSach = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Kho = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_SoLuong = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1214, 773));

        jLabel_ThemNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ThemNhanVien.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel_ThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ThemNhanVien.setText("Thêm sách");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(1170, 597));

        jLabel_ISBN.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_ISBN.setText("ISBN");

        jLabel_TenSach.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TenSach.setText("Tên sách");

        jLabel_DonGia.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_DonGia.setText("Đơn giá");

        jLabel_TenLoaiSach.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TenLoaiSach.setText("Loại sách");

        jLabel_TacGia.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_TacGia.setText("Tác giả");

        jLabel_NhaXuatBan.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_NhaXuatBan.setText("Nhà xuất bản");

        jLabel_NamXuatBan.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_NamXuatBan.setText("Năm xuất bản");

        jButton_ThemSach.setBackground(new java.awt.Color(102, 102, 0));
        jButton_ThemSach.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_ThemSach.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThemSach.setText("Thêm");
        jButton_ThemSach.setBorder(null);
        jButton_ThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemSachActionPerformed(evt);
            }
        });

        jButton_HuyBo.setBackground(new java.awt.Color(153, 0, 51));
        jButton_HuyBo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_HuyBo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_HuyBo.setText("Hủy bỏ");
        jButton_HuyBo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_HuyBoMouseClicked(evt);
            }
        });

        jTextField_TenSach.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_TenSach.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_TenSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_ISBN.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_ISBN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_ISBN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_TacGia.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_TacGia.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_TacGia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_NhaXuatBan.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_NhaXuatBan.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_NhaXuatBan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_NamXuatBan.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_NamXuatBan.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_NamXuatBan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_ThemAnh.setBackground(new java.awt.Color(102, 102, 0));
        jButton_ThemAnh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton_ThemAnh.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThemAnh.setText("Thêm ảnh");
        jButton_ThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemAnhActionPerformed(evt);
            }
        });

        jTextField_DonGia.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_DonGia.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextField_DonGia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(327, 342));

        jLabel_AnhDaiDien.setBackground(new java.awt.Color(204, 255, 153));
        jLabel_AnhDaiDien.setPreferredSize(new java.awt.Dimension(327, 342));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_AnhDaiDien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_AnhDaiDien, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        jComboBox_LoaiSach.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jComboBox_LoaiSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiểu thuyết", "Lịch sử", "Thiếu nhi", "Văn hóa xã hội", "Tâm lý, tình cảm" }));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Kho");

        jComboBox_Kho.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jComboBox_Kho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FAHASA Tân Định", "FAHASA Nguyễn Huệ", "FAHASA Phú Nhuận", "FAHASA Gò Vấp", "FAHASA Lạc Xuân" }));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Số lượng");

        jSpinner_SoLuong.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jSpinner_SoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_ThemAnh)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NamXuatBan)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_TenLoaiSach)
                                .addComponent(jLabel_NhaXuatBan)
                                .addComponent(jLabel_TacGia)
                                .addComponent(jLabel_DonGia)
                                .addComponent(jLabel_TenSach)
                                .addComponent(jLabel_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_NhaXuatBan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_TacGia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_DonGia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_TenSach, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ISBN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_NamXuatBan)
                            .addComponent(jComboBox_Kho, 0, 490, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox_LoaiSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_TenLoaiSach)
                                .addComponent(jComboBox_LoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSpinner_SoLuong))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_ThemAnh)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_NamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_NamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_ThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox_Kho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ThemNhanVien)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_ThemNhanVien)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemSachActionPerformed
        // TODO add your handling code here:
        String ISBN = jTextField_ISBN.getText();
        String tenSach = jTextField_TenSach.getText();
        String tacGia = jTextField_TacGia.getText();
        String nhaXB = jTextField_NhaXuatBan.getText();
        int namXB = Integer.parseInt(jTextField_NamXuatBan.getText());
        String loaiSach = jComboBox_LoaiSach.getSelectedItem().toString();
        Double donGia = Double.valueOf(jTextField_DonGia.getText());
        int soLuong = (int)jSpinner_SoLuong.getValue();
        String tenKho = jComboBox_Kho.getSelectedItem().toString();
        Sach sach = null;
        if(anh != null){
            sach = new Sach(ISBN, tenSach, tacGia, namXB, nhaXB, soLuong, donGia, new LoaiSach("", loaiSach), new HinhAnh(anh), "Đang bán");
        }else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ảnh");
        }
        try {
            if(dsSach.addDataToTable(sach)){
                khoHang_dao = new KhoHang_DAO();
                KhoHang kh = khoHang_dao.getKhoTheoTenKho(tenKho);
                System.out.println(soLuong);
                chiTietKhoHang_dao.themChiTietKhoHang(new ChiTietKhoHang(createMaCTKH(), soLuong,  new Sach(sach.getISBN()), new KhoHang(kh.getMaKhoHang())));
            };
        } catch (SQLException ex) {
            Logger.getLogger(Sach_ThemSach.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       this.dispose();
    }//GEN-LAST:event_jButton_ThemSachActionPerformed


    private void jButton_ThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser frame_chonAnh = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("File ảnh", "png", "jpq", "jpeg", "gif");
        frame_chonAnh.setFileFilter(filter);
        frame_chonAnh.setAcceptAllFileFilterUsed(false);
        
        int returnValue = frame_chonAnh.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            String filePath = frame_chonAnh.getSelectedFile().getPath();
            
            
            Icon icon = new ImageScale().load(filePath, jLabel_AnhDaiDien.getWidth(), jLabel_AnhDaiDien.getHeight());
            jLabel_AnhDaiDien.setIcon(icon);
            
            image_url = new AddImageToData();
            String fileName =image_url.duaFileVaoThuMuc(new File(filePath), "src\\ServiceImage\\Sach_IMG", "/ServiceImage/Sach_IMG/");
            System.out.println(fileName);
            anh = fileName;
            
//            String tenFile = new File(filePath).getName();
        }
    }//GEN-LAST:event_jButton_ThemAnhActionPerformed

    private void jButton_HuyBoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_HuyBoMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_HuyBoMouseClicked
    public String createMaCTKH(){
        List<String> dsMaCT =  chiTietKhoHang_dao.getMaChiTietKhoHang();
        String lastMaCT = dsMaCT.get(dsMaCT.size()-1);
        String prefix = lastMaCT.substring(0, 4);
        String numberPart = lastMaCT.substring(4);
        int number = Integer.parseInt(numberPart);
        number++;
        String newNumberPart;
        if (number < 100) {
            newNumberPart = String.format("%02d", number); // Giữ 2 chữ số khi number < 100
        } else {
            newNumberPart = Integer.toString(number); // Sử dụng 3 chữ số khi number >= 100
        }
        return prefix + newNumberPart;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sach_ThemSach dialog = new Sach_ThemSach(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_HuyBo;
    private javax.swing.JButton jButton_ThemAnh;
    private javax.swing.JButton jButton_ThemSach;
    private javax.swing.JComboBox<String> jComboBox_Kho;
    private javax.swing.JComboBox<String> jComboBox_LoaiSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_AnhDaiDien;
    private javax.swing.JLabel jLabel_DonGia;
    private javax.swing.JLabel jLabel_ISBN;
    private javax.swing.JLabel jLabel_NamXuatBan;
    private javax.swing.JLabel jLabel_NhaXuatBan;
    private javax.swing.JLabel jLabel_TacGia;
    private javax.swing.JLabel jLabel_TenLoaiSach;
    private javax.swing.JLabel jLabel_TenSach;
    private javax.swing.JLabel jLabel_ThemNhanVien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner_SoLuong;
    private javax.swing.JTextField jTextField_DonGia;
    private javax.swing.JTextField jTextField_ISBN;
    private javax.swing.JTextField jTextField_NamXuatBan;
    private javax.swing.JTextField jTextField_NhaXuatBan;
    private javax.swing.JTextField jTextField_TacGia;
    private javax.swing.JTextField jTextField_TenSach;
    // End of variables declaration//GEN-END:variables
}
