/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import button.TableActionCellEditor;
import button.TableActionEvent;
import button.TableActionRender;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Huu Thai
 */
public class ThuKho_QuanLySach extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrangTKKho_GUI
     */
    public ThuKho_QuanLySach() {
        initComponents();
        SwingUtilities.invokeLater(() -> {
            this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
            BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
            ui.setNorthPane(null);
            
            
        });
        
        //Căn giữa các phần tử trong table
        canGiua_tableHeader();
        
        //Chỉnh kích thước các phần tử trong table
        Font font = new Font("Arial", Font.PLAIN, 18);
        tbl_dsSach.setFont(font);
        
        // Chỉnh kích thước table header
        Font fn = new Font("Arial", Font.BOLD, 18);
        tbl_dsSach.getTableHeader().setFont(fn);
        
        // Chỉnh màu xanh cho combobox
        Color customGreen = new Color(0, 128, 0);
        cb_chonTieuChi.setRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if (isSelected) {
                c.setBackground(customGreen);   // Màu nền khi mục được chọn
                c.setForeground(Color.WHITE);   // Màu chữ khi mục được chọn
            } else {
                c.setBackground(Color.white); // Màu nền cho các mục không được chọn
                c.setForeground(customGreen);      // Màu chữ cho các mục không được chọn
            }

            return c;
            }
        });
//        TableActionEvent event;
//        event = new TableActionEvent() {
//            @Override
//            public void onEdit(int row) {
//                 JOptionPane.showMessageDialog(null, "Simple Information Message");
//            }
//
//            @Override
//            public void onDelete(int row) {
//
//            }
//
//            @Override
//            public void onView(int row) {
//                JOptionPane.showMessageDialog(null, "Simple Information Message");
//            }
//        };
//        tbl_dsSach.getColumnModel().getColumn(6).setCellRenderer(new TableActionRender(1));
//        tbl_dsSach.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditor(event, 1));
    }
    
    public void canGiua_tableHeader() {
    // Căn giữa và chỉnh kích thước table header
        Font fn = new Font("Arial", Font.BOLD, 18);
        tbl_dsSach.getTableHeader().setFont(fn);
        
        // Lấy header của bảng
        JTableHeader header = tbl_dsSach.getTableHeader();
        
        // Tạo renderer để căn giữa header
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);

        // Thiết lập renderer cho header
        header.setDefaultRenderer(renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame6 = new javax.swing.JPanel();
        btn_xuatExcel = new javax.swing.JButton();
        btn_timKiem = new javax.swing.JButton();
        cb_chonTieuChi = new javax.swing.JComboBox<>();
        tf_timKiem = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        tbl_dsSach = new javax.swing.JTable();
        btn_lamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1612, 733));

        frame6.setBackground(new java.awt.Color(255, 255, 255));
        frame6.setPreferredSize(new java.awt.Dimension(1612, 733));
        frame6.setLayout(null);

        btn_xuatExcel.setBackground(new java.awt.Color(102, 102, 0));
        btn_xuatExcel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_xuatExcel.setForeground(new java.awt.Color(255, 255, 255));
        btn_xuatExcel.setText("Xuất excel");
        btn_xuatExcel.setPreferredSize(new java.awt.Dimension(120, 42));
        btn_xuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatExcelActionPerformed(evt);
            }
        });
        frame6.add(btn_xuatExcel);
        btn_xuatExcel.setBounds(30, 620, 130, 40);

        btn_timKiem.setBackground(new java.awt.Color(102, 102, 0));
        btn_timKiem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_timKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.setPreferredSize(new java.awt.Dimension(120, 42));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        frame6.add(btn_timKiem);
        btn_timKiem.setBounds(1340, 170, 120, 42);

        cb_chonTieuChi.setBackground(new java.awt.Color(102, 102, 0));
        cb_chonTieuChi.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cb_chonTieuChi.setForeground(new java.awt.Color(255, 255, 255));
        cb_chonTieuChi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiêu chí", "ISBN", "Loại sách", "Tác giả" }));
        cb_chonTieuChi.setMinimumSize(new java.awt.Dimension(72, 30));
        cb_chonTieuChi.setPreferredSize(new java.awt.Dimension(300, 42));
        frame6.add(cb_chonTieuChi);
        cb_chonTieuChi.setBounds(850, 170, 180, 42);

        tf_timKiem.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tf_timKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_timKiem.setPreferredSize(new java.awt.Dimension(140, 42));
        tf_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_timKiemActionPerformed(evt);
            }
        });
        frame6.add(tf_timKiem);
        tf_timKiem.setBounds(1050, 170, 280, 42);

        tbl_dsSach.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tbl_dsSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "MS001", "fgs", "214", "32", "23", ""},
                {"2", null, null, null, null, null, null},
                {"3", null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ISBN", "Tên sách", "Loại sách", "Số lượng", "Đơn giá (VNĐ)", ""
            }
        ));
        tbl_dsSach.setAutoscrolls(false);
        tbl_dsSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_dsSach.setRowHeight(40);
        tbl_dsSach.setShowGrid(true);
        jScrollPane.setViewportView(tbl_dsSach);

        frame6.add(jScrollPane);
        jScrollPane.setBounds(30, 230, 1470, 360);

        btn_lamMoi.setBackground(new java.awt.Color(102, 102, 0));
        btn_lamMoi.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_lamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.setPreferredSize(new java.awt.Dimension(120, 42));
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });
        frame6.add(btn_lamMoi);
        btn_lamMoi.setBounds(30, 170, 130, 42);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jLabel_QuanLyDanhSachSach.png"))); // NOI18N
        frame6.add(jLabel1);
        jLabel1.setBounds(510, 30, 550, 78);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anhnen.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1612, 733));
        frame6.add(jLabel2);
        jLabel2.setBounds(0, 0, 1612, 733);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame6, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xuatExcelActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void tf_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_timKiemActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xuatExcel;
    private javax.swing.JComboBox<String> cb_chonTieuChi;
    private javax.swing.JPanel frame6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable tbl_dsSach;
    private javax.swing.JTextField tf_timKiem;
    // End of variables declaration//GEN-END:variables
}
