/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package button;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author The Bao
 */
public class Btn_chiTiet extends javax.swing.JPanel {

    /**
     * Creates new form btn_chiTiet
     */
   public Btn_chiTiet() {
        initComponents();
        
        // Căn giữa nút "chi tiết" vào panel
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.CENTER; // Center the button
        add(btn_chiTiet, gbc);
        
        // Add action listener to the button
    }
    
   public void initEvent(TableActionEvent e, int row) {
    // Đảm bảo rằng không có listener nào được thêm nhiều lần
    for (ActionListener listener : btn_chiTiet.getActionListeners()) {
        btn_chiTiet.removeActionListener(listener);
    }
    btn_chiTiet.addActionListener((ActionEvent ae) -> {
        System.out.println("button.PanelAction.initEvent() - View button clicked");
        e.onView(row);
    });
    
    
}

    // End of variables declaration                   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_chiTiet = new javax.swing.JButton();

        btn_chiTiet.setBackground(new java.awt.Color(102, 102, 0));
        btn_chiTiet.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btn_chiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btn_chiTiet.setText("Xem");
        btn_chiTiet.setMaximumSize(new java.awt.Dimension(72, 28));
        btn_chiTiet.setPreferredSize(new java.awt.Dimension(200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_chiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn_chiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chiTiet;
    // End of variables declaration//GEN-END:variables
}
