/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package button;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Huu Thai
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }
    public void initEvent(TableActionEvent e, int row) {
    // Đảm bảo rằng không có listener nào được thêm nhiều lần
    for (ActionListener listener : jButton_Xem.getActionListeners()) {
        jButton_Xem.removeActionListener(listener);
    }
    jButton_Xem.addActionListener((ActionEvent ae) -> {
        System.out.println("button.PanelAction.initEvent() - View button clicked");
        e.onView(row);
    });
    for (ActionListener listener : jButton_Sua.getActionListeners()) {
        jButton_Sua.removeActionListener(listener);
    }
    jButton_Sua.addActionListener((ActionEvent ae) -> {
        e.onEdit(row);
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Xem = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 51));

        jButton_Xem.setBackground(new java.awt.Color(102, 102, 0));
        jButton_Xem.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton_Xem.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Xem.setText("Xem");
        jButton_Xem.setPreferredSize(new java.awt.Dimension(200, 60));

        jButton_Sua.setBackground(new java.awt.Color(102, 102, 0));
        jButton_Sua.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton_Sua.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Sua.setText("Sửa");
        jButton_Sua.setPreferredSize(new java.awt.Dimension(200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton_Xem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Xem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Xem;
    // End of variables declaration//GEN-END:variables
}
